In [1]:
import pandas as pd

print("Pandas loaded successfully!")

Pandas loaded successfully!

In [2]:
listings = pd.read_csv("../data/raw/listings.csv")

print("Listings dataset loaded successfully!")
print(listings.shape)

Listings dataset loaded successfully!
(96871, 79)

In [3]:
listings.columns.tolist()

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'availability_eoy',
 'number_of_reviews_ly',
 'estimated_occupancy_l365d',
 'estimated_revenue_l365d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [4]:
listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,13913,https://www.airbnb.com/rooms/13913,20250914034649,2025-09-16,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.87,4.78,4.78,NaN,f,2,1,1,0,0.30
1,15400,https://www.airbnb.com/rooms/15400,20250914034649,2025-09-16,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.84,4.93,4.74,NaN,f,1,1,0,0,0.51
2,17402,https://www.airbnb.com/rooms/17402,20250914034649,2025-09-16,city scrape,Very Central Modern 3-Bed/2 Bath By Oxford St W1,"You'll have a great time in this beautiful, cl...","Fitzrovia is a very desirable trendy, arty and...",https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.72,4.89,4.61,NaN,f,2,2,0,0,0.32
3,24328,https://www.airbnb.com/rooms/24328,20250914034649,2025-09-18,previous scrape,Battersea live/work artist house,"Artist house by SW Battersea Park, bright high...","- Battersea is a quiet family area, easy acces...",https://a0.muscache.com/pictures/9194b40f-c627...,41759,...,4.93,4.60,4.65,NaN,f,1,1,0,0,0.53
4,36274,https://www.airbnb.com/rooms/36274,20250914034649,2025-09-15,city scrape,Bright 1 bedroom apt off brick lane in Shoreditch,*Update June '25- Pump Installed to improve wa...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,133271,...,4.46,4.85,4.54,NaN,t,2,2,0,0,0.09

Data Profile

In [5]:
listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 96871 entries, 0 to 96870
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            96871 non-null  int64
 1   listing_url                                   96871 non-null  str
 2   scrape_id                                     96871 non-null  int64
 3   last_scraped                                  96871 non-null  str
 4   source                                        96871 non-null  str
 5   name                                          96871 non-null  str
 6   description                                   94421 non-null  str
 7   neighborhood_overview                         41208 non-null  str
 8   picture_url                                   96865 non-null  str
 9   host_id                                       96871 non-null  int64
 10  host_url                                      96871 non-null  str
 11  host_name                                     96828 non-null  str
 12  host_since                                    96830 non-null  str
 13  host_location                                 73100 non-null  str
 14  host_about                                    49833 non-null  str
 15  host_response_time                            65164 non-null  str
 16  host_response_rate                            65164 non-null  str
 17  host_acceptance_rate                          69111 non-null  str
 18  host_is_superhost                             95105 non-null  str
 19  host_thumbnail_url                            96830 non-null  str
 20  host_picture_url                              96830 non-null  str
 21  host_neighbourhood                            45850 non-null  str
 22  host_listings_count                           96830 non-null  float64
 23  host_total_listings_count                     96830 non-null  float64
 24  host_verifications                            96830 non-null  str
 25  host_has_profile_pic                          96830 non-null  str
 26  host_identity_verified                        96830 non-null  str
 27  neighbourhood                                 41209 non-null  str
 28  neighbourhood_cleansed                        96871 non-null  str
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      96871 non-null  float64
 31  longitude                                     96871 non-null  float64
 32  property_type                                 96871 non-null  str
 33  room_type                                     96871 non-null  str
 34  accommodates                                  96871 non-null  int64
 35  bathrooms                                     62025 non-null  float64
 36  bathrooms_text                                96718 non-null  str
 37  bedrooms                                      84096 non-null  float64
 38  beds                                          61951 non-null  float64
 39  amenities                                     96871 non-null  str
 40  price                                         61963 non-null  str
 41  minimum_nights                                96871 non-null  int64
 42  maximum_nights                                96871 non-null  int64
 43  minimum_minimum_nights                        96868 non-null  float64
 44  maximum_minimum_nights                        96868 non-null  float64
 45  minimum_maximum_nights                        96868 non-null  float64
 46  maximum_maximum_nights                        96868 non-null  float64
 47  minimum_nights_avg_ntm                        96871 non-null  float64
 48  maximum_nights_avg_ntm                        96871 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              92622 non-null  str
 51  availability_30                               96871 non-null  int64
 52  availability_60                               96871 non-null  int64
 53  availability_90                               96871 non-null  int64
 54  availability_365                              96871 non-null  int64
 55  calendar_last_scraped                         96871 non-null  str
 56  number_of_reviews                             96871 non-null  int64
 57  number_of_reviews_ltm                         96871 non-null  int64
 58  number_of_reviews_l30d                        96871 non-null  int64
 59  availability_eoy                              96871 non-null  int64
 60  number_of_reviews_ly                          96871 non-null  int64
 61  estimated_occupancy_l365d                     96871 non-null  int64
 62  estimated_revenue_l365d                       61963 non-null  float64
 63  first_review                                  72749 non-null  str
 64  last_review                                   72749 non-null  str
 65  review_scores_rating                          72749 non-null  float64
 66  review_scores_accuracy                        72734 non-null  float64
 67  review_scores_cleanliness                     72740 non-null  float64
 68  review_scores_checkin                         72706 non-null  float64
 69  review_scores_communication                   72729 non-null  float64
 70  review_scores_location                        72705 non-null  float64
 71  review_scores_value                           72705 non-null  float64
 72  license                                       0 non-null      float64
 73  instant_bookable                              96871 non-null  str
 74  calculated_host_listings_count                96871 non-null  int64
 75  calculated_host_listings_count_entire_homes   96871 non-null  int64
 76  calculated_host_listings_count_private_rooms  96871 non-null  int64
 77  calculated_host_listings_count_shared_rooms   96871 non-null  int64
 78  reviews_per_month                             72749 non-null  float64
dtypes: float64(25), int64(20), str(34)
memory usage: 227.7 MB

In [6]:
listings.isnull().sum().sort_values(ascending=False).head(20)

license                         96871
calendar_updated                96871
neighbourhood_group_cleansed    96871
neighborhood_overview           55663
neighbourhood                   55662
host_neighbourhood              51021
host_about                      47038
beds                            34920
price                           34908
estimated_revenue_l365d         34908
bathrooms                       34846
host_response_rate              31707
host_response_time              31707
host_acceptance_rate            27760
review_scores_location          24166
review_scores_value             24166
review_scores_checkin           24165
review_scores_communication     24142
review_scores_accuracy          24137
review_scores_cleanliness       24131
dtype: int64

In [7]:
listings.duplicated().sum()

np.int64(0)

In [8]:
(round(listings["price"].isnull().mean()*100,2))

np.float64(36.04)

In [9]:
listings["price"].head(20)

0      $70.00
1     $149.00
2     $411.00
3         NaN
4     $210.00
5     $280.00
6      $90.00
7      $61.00
8     $340.00
9      $49.00
10        NaN
11    $213.00
12        NaN
13     $96.00
14        NaN
15     $71.00
16        NaN
17     $48.00
18        NaN
19     $76.00
Name: price, dtype: str

In [10]:
listings[["price","beds","bathrooms","review_scores_rating"]].head(10)

     price  beds  bathrooms  review_scores_rating
0   $70.00   1.0        1.0                  4.85
1  $149.00   1.0        1.0                  4.80
2  $411.00   3.0        2.0                  4.77
3      NaN   NaN        NaN                  4.90
4  $210.00   0.0        1.0                  4.53
5  $280.00   3.0        1.5                  4.80
6   $90.00   1.0        0.0                  4.87
7   $61.00   1.0        1.0                  4.77
8  $340.00   4.0        2.0                  4.83
9   $49.00   1.0        1.0                  4.97

In [11]:
calendar = pd.read_csv("../data/raw/calendar.csv")
reviews = pd.read_csv("../data/raw/reviews.csv")
neighbourhoods = pd.read_csv("../data/raw/neighbourhoods.csv")

print("CALENDAR:", calendar.shape)
print("REVIEWS:", reviews.shape)
print("NEIGHBOURHOODS:", neighbourhoods.shape)

CALENDAR: (35357974, 7)
REVIEWS: (2097996, 6)
NEIGHBOURHOODS: (33, 2)

In [12]:
calendar.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,1196288722069341420,2025-09-15,f,NaN,NaN,1,1125
1,1196288722069341420,2025-09-16,f,NaN,NaN,1,1125
2,1196288722069341420,2025-09-17,f,NaN,NaN,1,1125
3,1196288722069341420,2025-09-18,f,NaN,NaN,1,1125
4,1196288722069341420,2025-09-19,f,NaN,NaN,1,1125

In [13]:
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,13913,80770,2010-08-18,177109,Michael,My girlfriend and I hadn't known Alina before ...
1,13913,367568,2011-07-11,19835707,Mathias,Alina was a really good host. The flat is clea...
2,13913,529579,2011-09-13,1110304,Kristin,Alina is an amazing host. She made me feel rig...
3,13913,595481,2011-10-03,1216358,Camilla,"Alina's place is so nice, the room is big and ..."
4,13913,612947,2011-10-09,490840,Jorik,"Nice location in Islington area, good for shor..."

In [14]:
neighbourhoods.head()

   neighbourhood_group         neighbourhood
0                  NaN  Barking and Dagenham
1                  NaN                Barnet
2                  NaN                Bexley
3                  NaN                 Brent
4                  NaN               Bromley